### ISSUE TITLE
Error : Cannot read property 'Date' of undefined (2.7.1)

### ISSUE THREAD

**Issue by Bari77** [flexmonster/pivot-angular#1]
Hello Flexmonster Team,

I use your component for Angular 7.2.9 app, since the last update (2.7.1), I got an error when i try to use pivot component :
![image](https://user-images.githubusercontent.com/20283367/54516655-d83b5a80-495f-11e9-987b-a3161a72908e.png)

PS : Worked on :
"flexmonster": "2.6.15",
"ng-flexmonster": "2.6.15-1"

Cordialy, Bari.

**Comment by Bari77** [comment]
For more informations :
We create a variable with "default" header like that :
`const data: Object = {
    'Date': { type: 'Date', caption: this.translate.instant('CENTRE_ANALYSES.CAPTIONS.GENERALE.Date')},
...};
`
ans we use it on pivot report object :
`dataSource: {
                    data: data
                },
`
before get datas.

**Comment by flexmonster** [comment]
Hello, Bari,


Thank you for writing to us.


Could you please provide us with some more details describing the problem, for example, screenshots, a sample, or a JSFiddle example?


Best Regards,
Flexmonster Team

**Comment by flexmonster** [comment]
Hello, Bari,

Thank you for writing to us.

Could you please provide us with some more details describing the problem, for example, screenshots, a sample, or a JSFiddle example?

Also, could you please specify if you are already the client of Flexmonster? We need this information for our records.

Best Regards,
Flexmonster Team

**Comment by Bari77** [comment]
Hello flexmonster team;

JSFiddle here : https://jsfiddle.net/cxmahp0n/2

PS : Yes we are Flexmonster client (Hitech software)

Best Regards,
Bari.

**Comment by flexmonster** [comment]
Hello, Bari,


Thank you for providing us with a JSFiddle demonstrating the issue.
It helped us to understand the problem that you encountered better.


The issue occurred on our side as well. 
We are currently working on a solution to this problem.
The fix will be available in the minor release with the ETA April 8.


Please let us know if this works for you.


Best Regards,
Flexmonster Team

**Comment by Bari77** [comment]
Hello, Flexmonster Team,

Thank you for your involvement.

Best Regards,
Bari.

**Comment by flexmonster** [comment]
Hello, Bari,

We are glad to inform you that the fix is now available in the minor release version 2.7.3 of Flexmonster.
You are welcome to update the component.

Best Regards,
Flexmonster Team

**Comment by flexmonster** [comment]
closing the issue
